#include <stdint.h>
namespace PacketId
{
		inline int8_t FAILURE = 0, CREATESUCCESS = 0, CREATE = 0, PLAYERSHOOT = 0, MOVE = 0, PLAYERTEXT = 0, TEXT = 0, SERVERPLAYERSHOOT = 0,
			DAMAGE = 0, UPDATE = 0, UPDATEACK = 0, NOTIFICATION = 0, NEWTICK = 0, INVSWAP = 0, USEITEM = 0, SHOWEFFECT = 0, HELLO = 0, GOTO = 0, INVDROP = 0,
			INVRESULT = 0, RECONNECT = 0, PING = 0, PONG = 0, MAPINFO = 0, LOAD = 0, PIC = 0, SETCONDITION = 0, TELEPORT = 0, USEPORTAL = 0, DEATH = 0, BUY = 0,
			BUYRESULT = 0, AOE = 0, GROUNDDAMAGE = 0, PLAYERHIT = 0, ENEMYHIT = 0, AOEACK = 0, SHOOTACK = 0, OTHERHIT = 0, SQUAREHIT = 0, GOTOACK = 0,
			EDITACCOUNTLIST = 0, ACCOUNTLIST = 0, QUESTOBJID = 0, CHOOSENAME = 0, NAMERESULT = 0, CREATEGUILD = 0, GUILDRESULT = 0, GUILDREMOVE = 0,
			GUILDINVITE = 0, ALLYSHOOT = 0, ENEMYSHOOT = 0, REQUESTTRADE = 0, TRADEREQUESTED = 0, TRADESTART = 0, CHANGETRADE = 0, TRADECHANGED = 0,
			ACCEPTTRADE = 0, CANCELTRADE = 0, TRADEDONE = 0, TRADEACCEPTED = 0, CLIENTSTAT = 0, CHECKCREDITS = 0, ESCAPE = 0, FILE = 0, INVITEDTOGUILD = 0,
			JOINGUILD = 0, CHANGEGUILDRANK = 0, PLAYSOUND = 0, GLOBALNOTIFICATION = 0, RESKIN = 0, PETUPGRADEREQUEST = 0, ACTIVEPET_UPDATE_REQUEST = 0,
			ACTIVEPETUPDATE = 0, NEWABILITY = 0, PETYARDUPDATE = 0, EVOLVEPET = 0, DELETEPET = 0, HATCHPET = 0, ENTERARENA = 0, IMMINENTARENA_WAVE = 0,
			ARENADEATH = 0, ACCEPTARENA_DEATH = 0, VERIFYEMAIL = 0, RESKINUNLOCK = 0, PASSWORDPROMPT = 0, QUESTFETCH_ASK = 0, QUESTREDEEM = 0,
			QUESTFETCH_RESPONSE = 0, QUESTREDEEM_RESPONSE = 0, PETCHANGE_FORM_MSG = 0, KEYINFO_REQUEST = 0, KEYINFO_RESPONSE = 0, 
			CLAIMLOGIN_REWARD_MSG = 0, LOGINREWARD_MSG = 0, QUESTROOM_MSG = 0, PETCHANGE_SKIN_MSG = 0, REALMHERO_LEFT_MSG;

		void SetZero()
		{
			FAILURE = 0; CREATESUCCESS = 0; CREATE = 0; PLAYERSHOOT = 0; MOVE = 0; PLAYERTEXT = 0; TEXT = 0; SERVERPLAYERSHOOT = 0;
			DAMAGE = 0; UPDATE = 0; UPDATEACK = 0; NOTIFICATION = 0; NEWTICK = 0; INVSWAP = 0; USEITEM = 0; SHOWEFFECT = 0; HELLO = 0; GOTO = 0; INVDROP = 0;
			INVRESULT = 0; RECONNECT = 0; PING = 0; PONG = 0; MAPINFO = 0; LOAD = 0; PIC = 0; SETCONDITION = 0; TELEPORT = 0; USEPORTAL = 0; DEATH = 0; BUY = 0;
			BUYRESULT = 0; AOE = 0; GROUNDDAMAGE = 0; PLAYERHIT = 0; ENEMYHIT = 0; AOEACK = 0; SHOOTACK = 0; OTHERHIT = 0; SQUAREHIT = 0; GOTOACK = 0;
			EDITACCOUNTLIST = 0; ACCOUNTLIST = 0; QUESTOBJID = 0; CHOOSENAME = 0; NAMERESULT = 0; CREATEGUILD = 0; GUILDRESULT = 0; GUILDREMOVE = 0;
			GUILDINVITE = 0; ALLYSHOOT = 0; ENEMYSHOOT = 0; REQUESTTRADE = 0; TRADEREQUESTED = 0; TRADESTART = 0; CHANGETRADE = 0; TRADECHANGED = 0;
			ACCEPTTRADE = 0; CANCELTRADE = 0; TRADEDONE = 0; TRADEACCEPTED = 0; CLIENTSTAT = 0; CHECKCREDITS = 0; ESCAPE = 0; FILE = 0; INVITEDTOGUILD = 0;
			JOINGUILD = 0; CHANGEGUILDRANK = 0; PLAYSOUND = 0; GLOBALNOTIFICATION = 0; RESKIN = 0; PETUPGRADEREQUEST = 0; ACTIVEPET_UPDATE_REQUEST = 0;
			ACTIVEPETUPDATE = 0; NEWABILITY = 0; PETYARDUPDATE = 0; EVOLVEPET = 0; DELETEPET = 0; HATCHPET = 0; ENTERARENA = 0; IMMINENTARENA_WAVE = 0;
			ARENADEATH = 0; ACCEPTARENA_DEATH = 0; VERIFYEMAIL = 0; RESKINUNLOCK = 0; PASSWORDPROMPT = 0; QUESTFETCH_ASK = 0; QUESTREDEEM = 0;
			QUESTFETCH_RESPONSE = 0; QUESTREDEEM_RESPONSE = 0; PETCHANGE_FORM_MSG = 0; KEYINFO_REQUEST = 0; KEYINFO_RESPONSE = 0;
			CLAIMLOGIN_REWARD_MSG = 0; LOGINREWARD_MSG = 0; QUESTROOM_MSG = 0; PETCHANGE_SKIN_MSG = 0; REALMHERO_LEFT_MSG = 0;
		}
}